using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _7thHeaven.Code
{
    /// <summary>
    /// static methods to list music and movie files found in FF7
    /// </summary>
    public static class FF7FileLister
    {
        /// <summary>
        /// Returns list of all music file names used in FF7
        /// </summary>
        /// <returns></returns>
        public static string[] GetMusicFiles()
        {
            return new string[]
            {
                "aseri.ogg",
                "aseri2.ogg",
                "ayasi.ogg",
                "barret.ogg",
                "bat.ogg",
                "bee.ogg",
                "bokujo.ogg",
                "boo.ogg",
                "cannon.ogg",
                "canyon.ogg",
                "cephiros.ogg",
                "chase.ogg",
                "chu.ogg",
                "chu2.ogg",
                "cinco.ogg",
                "cintro.ogg",
                "comical.ogg",
                "condor.ogg",
                "corel.ogg",
                "corneo.ogg",
                "costa.ogg",
                "crlost.ogg",
                "crwin.ogg",
                "date.ogg",
                "dokubo.ogg",
                "dun2.ogg",
                "earis.ogg",
                "earislo.ogg",
                "elec.ogg",
                "fan2.ogg",
                "fanfare.ogg",
                "fiddle.ogg",
                "fin.ogg",
                "geki.ogg",
                "gold1.ogg",
                "guitar2.ogg",
                "gun.ogg",
                "hen.ogg",
                "hiku.ogg",
                "horror.ogg",
                "iseki.ogg",
                "jukai.ogg",
                "junon.ogg",
                "jyro.ogg",
                "ketc.ogg",
                "kita.ogg",
                "kurai.ogg",
                "lb1.ogg",
                "lb2.ogg",
                "ld.ogg",
                "makoro.ogg",
                "mati.ogg",
                "mekyu.ogg",
                "mogu.ogg",
                "mura1.ogg",
                "nointro.ogg",
                "oa.ogg",
                "ob.ogg",
                "odds.ogg",
                "over2.ogg",
                "parade.ogg",
                "pj.ogg",
                "pre.ogg",
                "red.ogg",
                "rhythm.ogg",
                "riku.ogg",
                "ro.ogg",
                "rocket.ogg",
                "roll.ogg",
                "rukei.ogg",
                "sadbar.ogg",
                "sadsid.ogg",
                "sea.ogg",
                "seto.ogg",
                "si.ogg",
                "sid2.ogg",
                "sido.ogg",
                "siera.ogg",
                "sinra.ogg",
                "sinraslo.ogg",
                "snow.ogg",
                "ta.ogg",
                "tb.ogg",
                "tender.ogg",
                "tifa.ogg",
                "tm.ogg",
                "utai.ogg",
                "vincent.ogg",
                "walz.ogg",
                "weapon.ogg",
                "yado.ogg",
                "yufi.ogg",
                "yufi2.ogg",
                "yume.ogg"
            };
        }

        /// <summary>
        /// Returns dictionary of all movie files in FF7 where Key is movie file name and value is a List of where the movie file can be found on disc e.g. "ff7disc1"
        /// </summary>
        /// <returns></returns>
        public static Dictionary<string, string[]> GetMovieFiles()
        {
            string[] disc1 = new string[] { "ff7disc1" };
            string[] disc2 = new string[] { "ff7disc2" };
            string[] disc3 = new string[] { "ff7disc3" };
            string[] allDiscs = new string[] { "ff7disc1", "ff7disc2", "ff7disc3" };

            return new Dictionary<string, string[]>()
            {
                { "biglight.avi", disc2},
                { "bike.avi", disc1},
                { "biskdead.avi", disc1},
                { "boogdemo.avi", disc1},
                { "boogdown.avi", allDiscs},
                { "boogstar.avi", disc1},
                { "boogup.avi", allDiscs},
                { "brgnvl.avi", disc1},
                { "c_scene1.avi", disc2},
                { "c_scene2.avi", disc2},
                { "c_scene3.avi", disc2},
                { "canon.avi", disc2},
                { "canonh1p.avi", disc2},
                { "canonh3f.avi", disc2},
                { "canonht0.avi", disc2},
                { "canonht1.avi", disc2},
                { "canonht2.avi", disc2},
                { "canonon.avi", disc2},
                { "car_1209.avi", disc1},
                { "d_ropego.avi", allDiscs},
                { "d_ropein.avi", allDiscs},
                { "dumcrush.avi", disc2},
                { "earithdd.avi", disc1},
                { "eidoslogo.avi", allDiscs},
                { "ending1.avi", disc3},
                { "ending2.avi", disc3},
                { "ending3.avi", disc3},
                { "Explode.avi", allDiscs},
                { "fallpl.avi", disc1},
                { "fcar.avi", disc3},
                { "feelwin0.avi", disc2},
                { "feelwin1.avi", disc2},
                { "fship2.avi", allDiscs},
                { "funeral.avi", disc1},
                { "gelnica.avi", disc2},
                { "gold1.avi", disc1},
                { "gold2.avi", allDiscs},
                { "gold3.avi", allDiscs},
                { "gold4.avi", allDiscs},
                { "gold5.avi", allDiscs},
                { "gold6.avi", allDiscs},
                { "gold7.avi", disc1},
                { "gold7_2.avi", disc1},
                { "greatpit.avi", disc2},
                { "hiwind0.avi", disc1},
                { "hwindfly.avi", disc2},
                { "hwindjet.avi", disc2},
                { "jairofal.avi", disc1},
                { "jairofly.avi", disc1},
                { "jenova_e.avi", disc1},
                { "junair_d.avi", allDiscs},
                { "junair_u.avi", allDiscs},
                { "junelego.avi", allDiscs},
                { "junelein.avi", allDiscs},
                { "junin_go.avi", allDiscs},
                { "junin_in.avi", allDiscs},
                { "junon.avi", disc1},
                { "junsea.avi", disc2},
                { "last4_2.avi", disc3},
                { "last4_3.avi", disc3},
                { "last4_4.avi", disc3},
                { "lastflor.avi", disc3},
                { "lastmap.avi", disc3},
                { "loslake1.avi", disc2},
                { "lslmv.avi", disc2},
                { "mainplr.avi", disc1},
                { "meteofix.avi", disc2},
                { "meteosky.avi", disc2},
                { "mk8.avi", disc1},
                { "mkup.avi", disc1},
                { "monitor.avi", new string[] { "ff7disc1", "ff7disc2" } },
                { "mtcrl.avi", disc1},
                { "mtnvl.avi", disc1},
                { "mtnvl2.avi", disc1},
                { "nivlsfs.avi", disc1},
                { "northmk.avi", disc1},
                { "nrcrl.avi", disc2},
                { "nrcrl_b.avi", disc2},
                { "nvlmk.avi", disc1},
                { "ontrain.avi", disc1},
                { "opening.avi", disc1},
                { "parashot.avi", disc2},
                { "phoenix.avi", disc2},
                { "plrexp.avi", disc1},
                { "rckethit0.avi", disc2},
                { "rckethit1.avi", disc2},
                { "rcketoff.avi", disc2},
                { "rcktfail.avi", disc1},
                { "setogake.avi", disc1},
                { "smk.avi", disc1},
                { "southmk.avi", disc1},
                { "sqlogo.avi", allDiscs},
                { "u_ropego.avi", allDiscs},
                { "u_ropein.avi", allDiscs},
                { "weapon0.avi", disc2},
                { "weapon1.avi", disc2},
                { "weapon2.avi", disc2},
                { "weapon3.avi", disc2},
                { "weapon4.avi", disc2},
                { "weapon5.avi", disc2},
                { "wh2e2.avi", disc2},
                { "white2.avi", new string[] { "ff7disc2", "ff7disc3" } },
                { "zmind01.avi", disc2},
                { "zmind02.avi", disc2},
                { "zmind03.avi", disc2}
            };
        }
    }
}
